# Generated by Django 5.1.3 on 2025-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_techblog_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
