# Generated by Django 5.1.3 on 2025-02-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser'),
        ('myapp', '0004_alter_techblog_photo'),
    ]

    operations = [
    ]
