# Generated by Django 5.1.3 on 2025-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techblog',
            old_name='tittle',
            new_name='title',
        ),
    ]
